apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: die-roll-deployment
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.replicas.replicaCount }}
  template:
    metadata:
      labels:
        app: die-roll
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: die-roll
        ports:
        - containerPort: {{ .Values.service.internalport }}
