apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: die-roll
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: die-roll
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: die-roll
              servicePort: {{ .Values.service.externalport }}
