apiVersion: v1
kind: Service
metadata:
  name: die-roll
  namespace: {{ .Values.metadata.namespace }}
spec:
  ports:
    - port: {{ .Values.service.externalport }}
      targetPort: {{ .Values.service.internalport }}
      protocol: TCP
  type: NodePort
  selector:
    app: die-roll
